base_config_file: "e2e_delay_effect_base_config.yml"                                     # Path to config file which stores the structure and
                                                                            # the default simulation parameters.
simulation_name: "e2e_delay_effect"                                        # String identifying the experiment (folder created for it)
threads: 2                                                                  # number of parallel executions of simulations
non_product_groups:                                                         # list of keys from the config file, where instead of product, zipping should be applied for creating the single configs
  - [optimization.improvement_score_limit, simulator.run_ampl]
meta_config_values:                                                         # under this a full single config structure can be given, but
  infrastructure:                                                           # each value should be a list of values
    gml_file: ["../graphs/infras/valencia-haven/valencia-haven-1.gml", "../graphs/infras/valencia-haven/valencia-haven-2.gml", "../graphs/infras/valencia-haven/valencia-haven-3.gml", "../graphs/infras/valencia-haven/valencia-haven-4.gml"]
  service:
    connected_component_sizes: [[10], [10, 10], [10, 10, 10]]               # list of integers describing the number (by its length) and size of the connected
    sfc_delays: [[3, 50, 50], [5, 50, 50], [10, 50, 50], [15, 50, 50], [1000, 50, 50]]
    seed: [0, 1, 2, 3, 4]
  optimization:
    improvement_score_limit: [3, 2, 1, 0]
  simulator:
    run_ampl: [True, False, False, False]
