# configuration which is small enough to run the AMPL with the demo license
#================= Infrastructure description section =================#
infrastructure:
  gml_file: ""
  name: "infra"                                       # name of the graph object
  label: "id"                                         # GML node attribute to be used as graph node id
  time_interval_count: 12                             # the number of time frames for the optimization t \in (t0, t1)
  cluster_move_distances: [0.0025]              # list of lengths of each cluster's line mobility pattern where the cluster goes there and back
                                                      # during the simulated time interval. The list's length identifies the number of clusters.
                                                      # Measured in 'GPS coordinate' lengths
  unloaded_battery_alive_prob: 0.99                   # Probability having a not completly depleted battery by the end of the optimization
                                                      # time interval if no capacity is used on the mobile node. Same value is set for all mobile nodes
  full_loaded_battery_alive_prob: 0.2                 # Like above, but with fully loaded mobile node.
  seed: 0                                             # randomization seed
#================= Service description section =================#
service:
  name: "service"                                     # name of the graph object
  connected_component_sizes: [20]                      # list of integers describing the number (by its length) and size of the connected
                                                      # service graph components. Each components is a series parallel graph
  sfc_delays: [5, 10, 15]                                 # list of delay values, which the chains can take (infra GML measures them in ms)
  series_parallel_ratio: 0.7                          # ratio of the series and parallel operations at the service graph generation
  mobile_nfs_per_sfc: 10                               # The number of NFs in each SFC which must be located in the corresponding mobile cluster
                                                      # (if a chain is shorter, at most all of the NFs are set but not more).
  seed: 0                                             # randomization seed (can be different from infra, but they together define the task)
#================= Optimization description section =================#
optimization:
  time_interval_count: 12                             # same as infrastructure.time_interval_count
  coverage_threshold: 0.8                             # Least probability the cluster should be covered at all time instances.
  battery_threshold: 0.2                              # Least probability which the mobile clusters are not depleted by the end of the
                                                      # optimization interval with the allocated load.
  improvement_score_limit: 1
#================= Simulator settings =================#
simulator:
  log_file: "mapping.log"
  console_log_level: "DEBUG"
  file_log_level: "DEBUG"
  ampl_model_path: '../ampl/system-model.mod'                           # AMPL model location for the volatile resources model
  export_ampl_data_path: "../ampl/system-model-generated.dat"           # if given, the generated data is exported for inspection/outer solution
  run_heuristic: True                                                  # Flags to set which algoritms to run
  run_ampl: True
