base_config_file: "coverage_threshold_variation_base_config.yml"                                     # Path to config file which stores the structure and
                                                                            # the default simulation parameters.
simulation_name: "coverage_threshold_variation"                                        # String identifying the experiment (folder created for it)
threads: 2                                                                  # number of parallel executions of simulations
non_product_groups:                                                         # list of keys from the config file, where instead of product, zipping should be applied for creating the single configs
  - [optimization.improvement_score_limit, simulator.run_ampl]
meta_config_values:                                                         # under this a full single config structure can be given, but
  infrastructure:                                                           # each value should be a list of values
    gml_file: ["../graphs/infras/valencia-haven/valencia-haven-1.gml", "../graphs/infras/valencia-haven/valencia-haven-2.gml", "../graphs/infras/valencia-haven/valencia-haven-3.gml", "../graphs/infras/valencia-haven/valencia-haven-4.gml"]
  service:
    seed: [0, 1, 2, 3, 4, 5]
  optimization:
    # probability decreases from 95% at the 'reach' of the AP up to 0% at 1.2*'reach'
    coverage_threshold: [0.9, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 0.999]
    improvement_score_limit: [2, 1, 0]
  simulator:
    run_ampl: [True, False, False]
